DOMAIN = "solar_energy_flow"

HUB_DEVICE_SUFFIX = "hub"
PID_DEVICE_SUFFIX = "pid"
DIVIDER_DEVICE_SUFFIX = "divider"
CONSUMER_DEVICE_SUFFIX = "consumer"

CONSUMER_TYPE_CONTROLLED = "controlled"
CONSUMER_TYPE_BINARY = "binary"
CONF_CONSUMERS = "consumers"
CONSUMER_ID = "id"
CONSUMER_NAME = "name"
CONSUMER_TYPE = "type"
CONSUMER_ENABLE_CONTROL_MODE = "enable_control_mode"
CONSUMER_ENABLE_TARGET_ENTITY_ID = "enable_target_entity_id"
CONSUMER_STATE_ENTITY_ID = "state_entity_id"
CONSUMER_POWER_TARGET_ENTITY_ID = "power_target_entity_id"
CONSUMER_POWER_SERVICE = "power_service"
CONSUMER_VALUE_FIELD = "value_field"
CONSUMER_PRIORITY = "priority"
CONSUMER_MAX_POWER_W = "max_power_w"
CONSUMER_MIN_POWER_W = "min_power_w"
CONSUMER_ON_THRESHOLD_W = "on_threshold_w"
CONSUMER_OFF_THRESHOLD_W = "off_threshold_w"
CONSUMER_DEFAULT_START_DELAY_S = 60.0
CONSUMER_DEFAULT_STOP_DELAY_S = 300.0
CONSUMER_CONTROL_MODE_ONOFF = "onoff"
CONSUMER_CONTROL_MODE_PRESS = "press"
CONSUMER_DEFAULT_POWER_SERVICE = "number.set_value"
CONSUMER_DEFAULT_VALUE_FIELD = "value"
CONSUMER_MIN_RATE_LIMIT_SEC = 5.0
CONSUMER_POWER_DEADBAND_W = 10.0

CONF_BATTERY_SOC_ENTITY = "battery_soc_entity"
CONF_PROCESS_VALUE_ENTITY = "process_value_entity"
CONF_SETPOINT_ENTITY = "setpoint_entity"
CONF_OUTPUT_ENTITY = "output_entity"
CONF_GRID_POWER_ENTITY = "grid_power_entity"
CONF_NAME = "name"
CONF_PV_MIN = "pv_min"
CONF_PV_MAX = "pv_max"
CONF_SP_MIN = "sp_min"
CONF_SP_MAX = "sp_max"
CONF_GRID_MIN = "grid_min"
CONF_GRID_MAX = "grid_max"

# Options (PID tuning)
CONF_KP = "kp"
CONF_KI = "ki"
CONF_KD = "kd"
CONF_MIN_OUTPUT = "min_output"
CONF_MAX_OUTPUT = "max_output"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_ENABLED = "enabled"
CONF_INVERT_PV = "invert_pv"
CONF_INVERT_SP = "invert_sp"
CONF_GRID_POWER_INVERT = "grid_power_invert"
CONF_PID_MODE = "pid_mode"
CONF_GRID_LIMITER_ENABLED = "grid_limiter_enabled"
CONF_GRID_LIMITER_TYPE = "grid_limiter_type"
CONF_GRID_LIMITER_LIMIT_W = "grid_limiter_limit_w"
CONF_GRID_LIMITER_DEADBAND_W = "grid_limiter_deadband_w"
CONF_PID_DEADBAND = "pid_deadband"
CONF_RATE_LIMITER_ENABLED = "rate_limiter_enabled"
CONF_RATE_LIMIT = "rate_limit"
CONF_RUNTIME_MODE = "runtime_mode"
CONF_MANUAL_SP_VALUE = "manual_sp_value"
CONF_MANUAL_OUT_VALUE = "manual_out_value"
CONF_MAX_OUTPUT_STEP = "max_output_step"
CONF_OUTPUT_EPSILON = "output_epsilon"

PID_MODE_DIRECT = "direct"
PID_MODE_REVERSE = "reverse"

GRID_LIMITER_TYPE_IMPORT = "import"
GRID_LIMITER_TYPE_EXPORT = "export"

GRID_LIMITER_STATE_NORMAL = "normal"
GRID_LIMITER_STATE_LIMITING_IMPORT = "limiting_import"
GRID_LIMITER_STATE_LIMITING_EXPORT = "limiting_export"

DEFAULT_KP = 1.0
DEFAULT_KI = 0.1
DEFAULT_KD = 0.0
DEFAULT_MIN_OUTPUT = 0.0
DEFAULT_MAX_OUTPUT = 11000.0
DEFAULT_UPDATE_INTERVAL = 10
DEFAULT_ENABLED = True
DEFAULT_INVERT_PV = False
DEFAULT_INVERT_SP = False
DEFAULT_GRID_POWER_INVERT = False
DEFAULT_PID_MODE = PID_MODE_DIRECT
DEFAULT_GRID_LIMITER_ENABLED = False
DEFAULT_GRID_LIMITER_TYPE = GRID_LIMITER_TYPE_IMPORT
DEFAULT_GRID_LIMITER_LIMIT_W = 1000.0
DEFAULT_GRID_LIMITER_DEADBAND_W = 50.0
DEFAULT_PID_DEADBAND = 0.0
DEFAULT_RATE_LIMITER_ENABLED = False
DEFAULT_RATE_LIMIT = 0.0
DEFAULT_RUNTIME_MODE = "AUTO SP"
DEFAULT_MANUAL_SP_VALUE = 0.0
DEFAULT_MANUAL_OUT_VALUE = 0.0
DEFAULT_MAX_OUTPUT_STEP = 0.0
DEFAULT_OUTPUT_EPSILON = 0.0
DEFAULT_PV_MIN = 0.0
DEFAULT_PV_MAX = DEFAULT_MAX_OUTPUT
DEFAULT_SP_MIN = 0.0
DEFAULT_SP_MAX = DEFAULT_MAX_OUTPUT
DEFAULT_GRID_MIN = -DEFAULT_MAX_OUTPUT
DEFAULT_GRID_MAX = DEFAULT_MAX_OUTPUT

RUNTIME_MODE_AUTO_SP = "AUTO SP"
RUNTIME_MODE_MANUAL_SP = "MANUAL SP"
RUNTIME_MODE_HOLD = "HOLD"
RUNTIME_MODE_MANUAL_OUT = "MANUAL OUT"

PLATFORMS = ["sensor", "switch", "number", "select", "binary_sensor"]
